from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field


class ChartConfig(BaseModel):
    """Generic chart configuration that the frontend can render."""

    type: Literal["line", "bar", "pie", "table", "metric", "area"] = "line"
    x: str = "t"
    y: str = "v"
    series_field: Optional[str] = None
    value_format: Optional[str] = None
    options: Dict[str, Any] = Field(default_factory=dict)


class DynamicWidgetSpec(BaseModel):
    """Declarative widget description generated by an AI agent or a user."""

    model_config = ConfigDict(extra="ignore")

    id: Optional[str] = None
    title: str
    description: str = ""
    sql: str
    chart: ChartConfig = Field(default_factory=ChartConfig)
    language: str = "ko"
    site_id: Optional[str] = None
    created_at: Optional[str] = None
    meta: Dict[str, Any] = Field(default_factory=dict)


class GeneratedWidgetRequest(BaseModel):
    """Natural-language requirement for AI-generated widgets."""

    requirement: str
    language: str = "ko"
    site_id: Optional[str] = None
    preferred_chart: Optional[str] = None


class DynamicWidgetData(BaseModel):
    """Generic data payload for dynamic widgets."""

    rows: List[Dict[str, Any]] = Field(default_factory=list)
    meta: Dict[str, Any] = Field(default_factory=dict)

